require 'rubygems'; require 'json'
require 'twitter_friends/json_model/generic_json_parser'
require 'twitter_friends/json_model/json_tweet'
require 'twitter_friends/json_model/json_twitter_user'
require 'twitter_friends/json_model/public_timeline_parser'
require 'twitter_friends/json_model/friends_followers_parser'
require 'twitter_friends/json_model/user_parser'
